### ISSUE TITLE
404 error if posting to sentry.io

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/sentry#13]
I'm not sure if sentry changed the rest interface, or if the problem has been around for a while.

When I try to configure the appenderin a coldbox app with the sentry DSN, I get a 404 response when posting a log message.

If I adjust the code like this in the post() function, it works
```
restURL = getSentryUrl() & "/api/" & getProjectID() & "/store/";
```
see also https://docs.sentry.io/development/sdk-dev/overview/#a-working-example

**Comment by bdw429s** [comment]
@eppinger It's possible the API changed.  It's also possible that the hosted version of Sentry uses a different API then their open source docker version.  I've never actually used this module with sentry.io but always with a Docker container running the Sentry application on my own infrastructure (which is free)
I'm open to changing this to work with sentry.io but we need to figure out how to continue working with the other Sentry versions in use.

**Comment by jcberquist** [comment]
I suspect this has to do with an update of the API endpoints sentry uses. We are using this module with sentry.io directly, and it is still working for us. So I wonder if we are effectively being treated as legacy clients. @eppinger did you set up an account recently?

**Comment by eppinger** [comment]
i setup my account a week ago

**Comment by eppinger** [comment]
I have now also set up my own Docker instance and again I have to adjust the restURL accordingly.

The sentry version of my container: 10.1.0.dev00263aff


When I look at the official Javascript SDK (https://github.com/getsentry/sentry-javascript) and search for the store URL, the endpoint "/api/ projectnr /store/" is used everywhere

I can't find any information about when they introduced this change (https://develop.sentry.dev/sdk/store) and how to recognize the endpoint.

**Comment by bdw429s** [comment]
https://github.com/coldbox-modules/sentry/pull/15
