### ISSUE TITLE
Error with negative line numbers in tagContext

### ISSUE THREAD

**Issue by bockensm** [coldbox-modules/sentry#24]
Periodically I'll see an error where the tagContext has the error occuring at line -1:

![image](https://user-images.githubusercontent.com/2660751/125110136-d1ddc900-e0a9-11eb-8c4e-1bd1b9b8c542.png)

In this case, the SentryService component cannot handle it and throws an error.

**Comment by bdw429s** [comment]
Hi @bockensm somehow I don't think I ever saw this issue.  I assume the issue is in the funcLineNums.  If this is still a problem, can you send a pull to fix it?

**Comment by bockensm** [comment]
We've stopped using Sentry for this particular project so I can't comment as to whether this is still an issue. I'd be OK with this getting closed.
