### ISSUE TITLE
Variable TRACEPARENT is undefined

### ISSUE THREAD

**Issue by Cicco0** [coldbox-modules/sentry#37]
I noticed an issue in the implementation of cfthread within the module. A variable `traceParent`, which is defined outside the thread, is referenced within the thread but not explicitly passed, leading to an error.

The relevant snippet in the module looks like this:
https://github.com/coldbox-modules/sentry/blob/8154d60984b33c627c61ca873b3d0869245ec6d4/models/SentryService.cfc#L791-L807

Here, `traceParent` is used inside the `cfthread` block, but it is not passed as an argument to the thread. This causes an error:
```
Variable TRACEPARENT is undefined.
```

**Steps to Reproduce**

1. Install the coldbox-modules/sentry module.
2. Configure and run the module in a way that invokes the above cfthread implementation.
3. Observe that the error occurs because traceParent is not defined in the thread context.

Thank you for maintaining this great module! Please let me know if I can assist further with this issue.

**Comment by bdw429s** [comment]
Very sorry I never saw this. Most notifications from Github get lost from me which is why JIRA is a better place for tickets.  @jclausen this appears to be from your commit a month ago, can you address it?

**Comment by jclausen** [comment]
This should be resolved no in v2.1.4
