### ISSUE TITLE
Improve function name reporting in stack traces

### ISSUE THREAD

**Issue by jcberquist** [coldbox-modules/sentry#6]
Right now each stack item gets a function name added to via the following lines of code:
```cfc
// The name of the function being called
if (i == 1) {
    thisStackItem["function"] = "column #thisTCItem["COLUMN"]#";
} else {
    thisStackItem["function"] = thisTCItem["ID"];
}
```
On Lucee this effectively means every stack trace ends up rendered in the sentry interface with the first item showing something such as:
```
myFile.cfc in **column 0** at line 123
```
and all subsequent lines as:
```
myOtherFile.cfc in **??** at line 321
```
On ACF this supplies function names such as `CF_TEMPLATEPROXY` after the first line, which is also going to be set to `column 0`, as far as I can see.

I have created a component that, given a template path and a line number, will return the name of the function that line number is part of (if any); this way the actual CFML function names can be seen in the stack. I would like incorporate into this project, either directly, or as a dependency. Is this acceptable, and, if so, do you have a preference for how to go about it?

**Comment by bdw429s** [comment]
@jcberquist Thanks for addressing this.  The sentry lib we forked was originally written for Adobe CF only.  How is the performance of your method, keep in mind there may be dozens of files in the stack.  If your component is on forgebox as a separate project, we can include it as a dependency, otherwise, we can just add it into the models and use Wirebox to inject it.  Having a cfproperty will also allow people to use the setting if they are wanting to use this library outside of ColdBox (we'll need to update the read me to account).

So, I'd say send over a pull and we can start reviewing it.

**Comment by jcberquist** [comment]
Thanks @bdw429s - I decided to add my component as a module to ForgeBox:

https://www.forgebox.io/view/funclinenums
https://github.com/jcberquist/function-linenums

I do think performance could be a concern. I tested it with the FW/1 source (~3000 lines) and it can take it anywhere from ~70ms to ~150ms to walk the file (depending on the machine and engine it is running on - Lucee is a bit faster). Most files are much shorter (mine are anyways) and it is pretty fast on those - it takes ~25ms to process `BaseSpec.cfc` from TestBox (~1300 lines) and even shorter files are really fast. Of course that could still add up, though it does cache the parse so you would only pay that cost once per template.

Now I don't mind that cost myself, but I could see you might want to avoid it. So perhaps it could be done asynchronously? It also occurs to me that you could just make available a UDF for for the computing of the function names that defaults to the current behavior (or does nothing, since I don't think the current behavior has much value :smile:) and I could use that UDF with my component to get the behavior I want without forcing it on everyone by default.

**Comment by bdw429s** [comment]
@jcberquist Lucee provides the function name in `callStackGet()` which doesn't help us _directly_ here, but is there a way to tap into the Lucee internals that store that function name for our purposes?

Regarding performance, I usually run Sentry async so that's less of a concern other than the potential increase in processing it may put on a server with lots of errors.  On that note-- I need to check and make sure the async stuff in Sentry applies to ALL the processing, not just the HTTP call.

**Comment by bdw429s** [comment]
@jcberquist Check this out:

```js
PageSourceImpl = createObject( 'java', 'lucee.runtime.PageSourceImpl' );		
source = PageSourceImpl.best( getPageContext().getPageSources( makePathRelative( expandPath( '/handlers/main.cfc' ) ) ) ).loadPage( getPageContext(), true );

for( udf in source.udfs ) {
	dump( 'Function #udf.getFunctionName()# starts on line #udf.getStartLine()# and ends on line #udf.getEndLine()#' );
}
```

The makePathRelative() function is just something that takes an absolute path and converts it to use a mapping so it's relative.  I assume we'll be starting with absolute paths.  You can find that function in CommandBox and TestBox for similar purposes.   

But basically, we can loop over the page source class in Lucee and find out what UDFs are in that page and what lines they start and stop on.  Do you want to see if this works any better?  The only thing I'm not sure of is if it will cause extra compilation if we don't use the same relative file path that Lucee has already used to compile the page.  I'm not sure if Lucee is smart enough to know if `/modules/foo/models/bar.cfc` is the same file as `/foo/models/bar.cfc.`

Actually, you know what-- we can get the same data this way:

```js		
for( udf in getComponentMetaData( 'handlers.main' ).functions ) {
	dump( 'Function #udf.name# starts on line #udf.position.start# and ends on line #udf.position.end#' );
}
```

I bet that uses the same underlying classes but is less likely to break in the future.  Thoughts?  It's Lucee specific for sure since Adobe CF doesn't include that information.

**Comment by jcberquist** [comment]
I will take a look when I am back at my computer. A couple of things do occur to me. To use your last example, wouldn’t you have to be able to get a component mapping to use it? Presumably you could, but you would need to be able to figure out a mapping from an absolute path - is that right? I see the `makePathRelative()` function in the first example, could that be used?

The other thing is that I think this will only make a difference on the first time a template is seen since after that the same computations will be done either way (looping through the functions to see where the particular line in the stack falls).

**Comment by jcberquist** [comment]
I have now actually been able to take a look at this. As you say, this would be a Lucee only approach since ACF does not return line numbers in the metadata. I do have a couple of thoughts (repeating myself).

In order to use this approach, I would need to be able to compute the component dotted path given an absolute path. I think this would be doable in most (all?) cases using a combination of the webroot and `getApplicationMetadata()` to find all defined mappings. However, in my testing if components have been created inline via a relative path and then their metadata is accessed via a mapping, or if they have been created using one mapping and their metadata is accessed via a different mapping, it looks to me like they get recompiled (this assumes that mapping hasn't been used before, of course - so this probably is a really minor issue). Also, while I don't think it is necessarily a common scenario, can you get function names for functions defined in `.cfm` templates this way?

After the function name and line numbers are obtained, the computation cost on each exception would be the same whether the information came from the metadata or from a parse - so I think the approach chosen will not make a lasting difference to the "processing it may put on a server with lots of errors." It would possibly make a difference to not do it at all - though in my tests after the function line numbers in a file are obtained you will mostly see sub millisecond times for the computation of the function name on each tag context line. If everything is done async I don't think there is going to be a noticeable difference in the two approaches.

**Comment by bdw429s** [comment]
> As you say, this would be a Lucee only approach since ACF does not return line numbers in the metadata. 

Correct, but as we already have a workable solution for Adobe CF parsing the inner class name we only need this to work for Lucee.

> In order to use this approach, I would need to be able to compute the component dotted path given an absolute path. I think this would be doable in most (all?) cases using a combination of the webroot and getApplicationMetadata() to find all defined mappings.

Not necessarily, you're forgetting about CF mappings created int the web or server context.  but no matter, the `makePathRelative()` function I mentioned before will make ANY path relative.  It will create mappings as necessary to make it happen.  Now, that function doesn't try to match any existing mappings, it simply creates one that points to the root of the drive (or farther up if there are folders containing dots).  The logic may be able to be optimized for files already in the webroot to try and guess what mapping was most likely used to compile the .cfc and therefore more likely to hit a class file already in cache.

> can you get function names for functions defined in .cfm templates this way?

My java code I showed would probably work for that.  I'm pretty sure those page source classes are for both .cfc and .cfm files.

> After the function name and line numbers are obtained, the computation cost on each exception would be the same whether the information came from the metadata or from a parse 

I'm not sure what you're saying there.  The processing to obtain the line numbers is precisely what we're discussing so I'm not sure why you'd exclude it from the conversation.  

>  It would possibly make a difference to not do it at all 

Well, yes, obviously.  Doing nothing will be faster then doing something, but I'm not sure what value that point has :)

>  though in my tests after the function line numbers in a file are obtained you will mostly see sub millisecond times for the computation of the function name on each tag context line.

Yes, matching the line number to a function once we know where the functions are is just a simple short circuited loop, but then again I think the "heavy lifting" here has always been finding out where the functions live in the first place.

> If everything is done async I don't think there is going to be a noticeable difference in the two approaches.

Well again, CPU cycles are still CPU cycles, even if they run in a thread. So if Sentry is async it may not hold up the original HTTP request, but it can potentially load the server.  My assumptions here are
* Lucee parsing and compilation will be faster and more optimized
* Lucee's compilation will be cached whereas your CFC will need to reparse for every error (or worse, every time a file appears in a given context) unless you add a layer of caching in-- something Lucee is already doing for is with its page source classes.

**Comment by jcberquist** [comment]
> we already have a workable solution for Adobe CF parsing the inner class name

Are you referring to looking at the stack trace and figuring out the function name from that, since ACF uses the original function name in its Java classes?

> The processing to obtain the line numbers is precisely what we're discussing so I'm not sure why you'd exclude it from the conversation.

> Well, yes, obviously. Doing nothing will be faster then doing something, but I'm not sure what value that point has :)

> Lucee's compilation will be cached whereas your CFC will need to reparse for every error (or worse, every time a file appears in a given context) unless you add a layer of caching in

I am sorry, I guess I am really failing to be clear. I said early on, regarding my proposed approach, that "it does cache the parse so you would only pay that cost once per template". Of course it would not make sense to do this if it had to parse every template every time - but it doesn't. It caches every absolute path (and it declares itself as a singleton, so it would be in the Application scope), so it would only ever parse a given template once. That is why I said that if performance is a concern, the ongoing computations done by the two approaches would be exactly the same - so if you were concerned about performance, the solution would be to do nothing, not to pick one of these approaches over the other.

> Lucee parsing and compilation will be faster and more optimized

This I think is true, but it is not clear to me that it is faster in every case. The real advantage it seems to me would be that ideally we can get at the already cached code when processing - and my expressed concern is that if we make new mappings on the fly, it will be forced to recompile. I think I was definitely seeing that in my tests. If it is recompiling, then I think any processing gain is lost. And as I said above, since both approaches would be caching, after that initial parse/compile, there is no processing difference betweeen the two approaches.

**Comment by bdw429s** [comment]
@jcberquist Sorry, I got a little side tracked with client stuff.  Yes, sorry, I didn't catch that you have caching as a part of your solution.  I would still prefer to use the metadata from Lucee if we can, but but if you test it and it performs the same then I'm fine either way.  Just ensure that if something goes horribly wrong in your parser, that it doesn't kill the request.  perhaps just log to the console if that happens and keep moving.

**Comment by jcberquist** [comment]
So the answer for Lucee is not clear to me. In my testing when a new mapping is first created, then Lucee is going to recompile classes and write them to disk for the new mapping - this is significantly slower than just parsing the file. Looking at the `makePathRelative()` function, since it creates drive root mappings, I would expect using this technique to require each file to be recompiled at least once. But once the new compiled classes are present on disk, then using Lucee's metadata is going to be faster (i.e. after a server restart or the like).  Although (obviously) if a file is changed on disk, then Lucee will again recompile for the drive root mapping, and that will again take longer than just parsing the file.

I am interested still in how you are thinking of getting function names out of ACF? If there is a good technique for that, then I think I would be fine with using the metadata approach for Lucee (I am okay with it anyways if that is your preference), but if there isn't a good other technique for ACF then I would push more for the parsing of the files, which will work across the engines.

As a side question - the thought of having a drive root (or root folder) mapping present on a production server makes me somewhat nervous, though I am not sure what could be done with it - do you have thoughts on that?

**Comment by bdw429s** [comment]
I had said earlier that the `makepathrelative()` function could be enhanced to scan visible mapping as well as "optimize" file paths that appeared to be in the webroot by assuming `/relative/to/webroot/path/to/File.cfc`. The original function was written for CommandBox where there really is no web root so in that case I didn't care about it.

> I am interested still in how you are thinking of getting function names out of ACF? 

Sorry, I thought this was already working for ACF and we only needed a Lucee workaround.  Is this not the case?

**Comment by jcberquist** [comment]
In ACF it puts IDs such as `CF_UDFMETHOD` and `CF_TEMPLATEPROXY` in the tag context array. I don't consider that very helpful, since you don't get the name of the function running. Now in the raw_trace field, it provides the name of the inner class, and it seems to name that after the actual name of the function:
```
at cftest2ecfc78471891$funcMYFUNCTION.runFunction(test.cfc:8)
```
So you could use regex to get the function name out of that, but of course it will always be uppercase.

**Comment by bdw429s** [comment]
Ah, I see.  My apologies, I was thinking from the get-go that Adobe was doing what we needed and we only needed a solution for Lucee.  That sucks.  Well, if that's the case, then yeah, let's give your library a whirl since it will give us an improved and consistent experience across all the engines.  Thanks for sticking to the conversation to get me straightened out :)
