### ISSUE TITLE
sentry not compatible with BaseHandler of HMVC rest module

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/sentry#9]
The sentry module is doing all kind of things automatically. 
in SentryAppender.logMessage it is checking
```
		if( isStruct( extraInfo ) && extraInfo.keyExists( "StackTrace" ) ){
			getProperty( 'sentryService' ).captureException(
				exception = extraInfo,
				level 	= level,
				message = message,
				logger = loggerCat
			);
```
but captureException also needs the extrainfo.message key and the extrainfo.detail key, otherwise the captureException call will fail.
The REST basehandler, only has the stacktrace and httpData keys, so it will fail.
Two solutions: change the basehandler, or do some additional checking for  missing keys

**Comment by bdw429s** [comment]
Good catch.  This is one of the few annoying times where CF's loose typing is a pain and I wish this were Java where I could test `extraInfo` to be an instance of a certain class and then be guaranteed that specific fields would exist on the object.  I don't like the fact that the base handler is handing around an object that is sort-of like an exception but doesn't contain all the standard pieces.  That said, the extra checks don't hurt anything in Sentry.  I'd say we check for the keys and just default to an empty string or something, but that is sort of odd to not even have a message!  A message is typically the one required thing you can always count on existing in an exception object.  Maybe if it doesn't exist, we can try and default it to something else useful.
